version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - static-data:/vol/web
    env_file:
      - .dbenv
    restart: allways
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .dbenv
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/web
    restart: always
    depends_on:
      - backend

volumes:
  postgres-data:
  static-data: