version: '3.9'

services:
  backend:
    container_name: deploy_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - static-data:/vol/web
    env_file:
      - .dbenv
    restart: always
    depends_on:
      - db

  db:
    container_name: deploy_db
    image: postgres:13-alpine
    env_file:
      - .dbenv
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    container_name: deploy_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/web
    restart: always
    depends_on:
      - backend

volumes:
  postgres-data:
  static-data: