# Generated by Django 3.2.24 on 2024-02-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240211_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
